# Mastering NumPy - 1. Working with NumPy Arrays

## 1.6 NumPy Array Operations

In [29]:
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
print(type(my_list), type(my_array))

<class 'list'> <class 'numpy.ndarray'>


In [30]:
my_array + 2

array([ 4, 16,  8, 10])

In [31]:
my_array - 1

array([ 1, 13,  5,  7])

In [32]:
my_array * 2

array([ 4, 28, 12, 16])

In [33]:
my_array / 2

array([1., 7., 3., 4.])

In [37]:
second_array = np.zeros(4)+3
second_array

array([3., 3., 3., 3.])

In [38]:
my_array - second_array

array([-1., 11.,  3.,  5.])

In [39]:
second_array / my_array

array([1.5       , 0.21428571, 0.5       , 0.375     ])

In [42]:
second_array = np.ones(4) + 3
second_array

array([4., 4., 4., 4.])

In [43]:
my_array - second_array

array([-2., 10.,  2.,  4.])

In [44]:
second_array / my_array

array([2.        , 0.28571429, 0.66666667, 0.5       ])

In [45]:
second_array = np.identity(4)
second_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
second_array = np.identity(4) + 3
second_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [51]:
my_array - second_array

array([[-2., 11.,  3.,  5.],
       [-1., 10.,  3.,  5.],
       [-1., 11.,  2.,  5.],
       [-1., 11.,  3.,  4.]])

In [52]:
second_array / my_array

array([[2.        , 0.21428571, 0.5       , 0.375     ],
       [1.5       , 0.28571429, 0.5       , 0.375     ],
       [1.5       , 0.21428571, 0.66666667, 0.375     ],
       [1.5       , 0.21428571, 0.5       , 0.5       ]])

In [54]:
x = np.arange(3, 7, 0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [56]:
x = np.linspace(1.2, 40.5, num = 20)
x

array([ 1.2       ,  3.26842105,  5.33684211,  7.40526316,  9.47368421,
       11.54210526, 13.61052632, 15.67894737, 17.74736842, 19.81578947,
       21.88421053, 23.95263158, 26.02105263, 28.08947368, 30.15789474,
       32.22631579, 34.29473684, 36.36315789, 38.43157895, 40.5       ])

In [57]:
np.geomspace(1, 625, num = 5)

array([  1.,   5.,  25., 125., 625.])

In [58]:
np.logspace(3, 4, num = 5)

array([ 1000.        ,  1778.27941004,  3162.27766017,  5623.4132519 ,
       10000.        ])

In [59]:
np.logspace(np.log10(3), np.log10(4), num = 5)

array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [65]:
# Compare two Arrays: done in element-wise and return a boolean vector
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
print(x == y, type(x == y), (x == y).dtype)

[ True False False  True] <class 'numpy.ndarray'> bool


In [66]:
np.array_equal(x, y)

False

In [67]:
x < y

array([False,  True,  True, False])

In [69]:
x = np.array([0,1,0,0], dtype = bool)
y = np.array([1,1,0,1], dtype = bool)
print("logical_or:", np.logical_or(x, y))
print("logical_and:", np.logical_and(x, y))

logical_or: [ True  True False  True]
logical_and: [False  True False False]


In [70]:
x = np.array([12,16,57,11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True])

In [75]:
# Transcendental functions: e.g. exponential, logarithm, trigonometric
x = np.array([1,2,3,4])
print(np.exp(x))
print(np.log(x))
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [ ]:
# Transpose of a Matrix
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [82]:
x = np.arange(9).reshape((3,3))
print("x=", x, "\n", "x.T=", x.T)

x= [[0 1 2]
 [3 4 5]
 [6 7 8]] 
 x.T= [[0 3 6]
 [1 4 7]
 [2 5 8]]


In [83]:
x = np.arange(6).reshape(2,3)
print("x=", x, "\n", "x.T=", x.T)

x= [[0 1 2]
 [3 4 5]] 
 x.T= [[0 3]
 [1 4]
 [2 5]]


In [85]:
# Same of the precdeing statistical method of NumPy
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
np.sum(x)

np.int64(36)

In [87]:
np.amin(x)

np.int64(0)

In [88]:
np.amax(x)

np.int64(8)

In [89]:
np.amin(x, axis=0)

array([0, 1, 2])

In [90]:
np.amin(x, axis=1)

array([0, 3, 6])

In [91]:
np.percentile(x, 80)

np.float64(6.4)

In [94]:
x = np.array([1, -21, 3, -3])
print(np.argmax(x), np.argmin(x))

2 1


In [96]:
x = np.array([[2,3,5],[20,12,4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [97]:
np.mean(x)

np.float64(7.666666666666667)

In [98]:
np.mean(x, axis=0)

array([11. ,  7.5,  4.5])

In [99]:
np.mean(x, axis=1)

array([ 3.33333333, 12.        ])

In [100]:
np.median(x)

np.float64(4.5)

In [101]:
np.std(x)

np.float64(6.394442031083626)