# Mastering NumPy - 1. Working with NumPy Arrays

## 1.8 Indexing, Slicing, Reshaping, Resizing, and Broadcasting

### 1.8.1 Indexing

In [ ]:

x = ["China", "France", "Germeny", "Belgium"]
x[2]

'Germeny'

In [2]:
x = ('USA', 3, "France", 4)
x[1]

3

In [8]:
# Indexing - 1) Field Access
import numpy as np
x = np.arange(10)
print(x)
print(f"x[5]={x[5]}, x[-2]={x[-2]}, x[2:8]={x[2:8]}")
print(f"x[:]={x[:]}, x[2:8:2]={x[2:8:2]}")

[0 1 2 3 4 5 6 7 8 9]
x[5]=5, x[-2]=8, x[2:8]=[2 3 4 5 6 7]
x[:]=[0 1 2 3 4 5 6 7 8 9], x[2:8:2]=[2 4 6]


### 1.8.2 Slicing

In [16]:
# Slice the n-dimensional array as [slicing in x-axis, slicing in y-axis]
x = np.reshape(np.arange(16),(4,4))
print(f"x=\n{x}\nx[1:3]=\n{x[1:3]}\nx[:,1:3]=\n{x[:,1:3]}\nx[1:3,1:3]=\n{x[1:3,1:3]}")

x=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
x[1:3]=
[[ 4  5  6  7]
 [ 8  9 10 11]]
x[:,1:3]=
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
x[1:3,1:3]=
[[ 5  6]
 [ 9 10]]


In [22]:
x = np.reshape(np.arange(16),(4,4))
print(f"x=\n{x}")
print(f"x[[0,1,2,3],[0,1,3,2]]=\n{x[[0,1,2,3],[0,1,3,2]]}")

x=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
x[[0,1,2,3],[0,1,3,2]]=
[ 0  5 11 14]


### 1.8.3 Reshaping

### 1.8.4 Resizing

In [25]:
np.arange(16).reshape(4,4)
print(f"reshaped x =\n{x}")
print(f"resized x in (2,2) =\n{np.resize(x,(2,2))}")
print(f"resized x in (6,6) =\n{np.resize(x,(6,6))}")

reshaped x =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
resized x in (2,2) =
[[0 1]
 [2 3]]
resized x in (6,6) =
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15  0  1]
 [ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15  0  1  2  3]]


### 1.8.5 Broadcasting

In [ ]:
x = np.arange(16).reshape(4,4)
y = np.arange(6).reshape(2,3)
print(f"x + y =\n{x+y}")

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [27]:
print(f"x * y =\n{x*y}")

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [28]:
x = np.arange(16).reshape(4,4)
y = np.arange(4)
print(f"x * y =\n{x*y}")

x * y =
[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]]


In [29]:
x = np.arange(4).reshape(2,2)
y = np.arange(2).reshape(1,2)
print(f"x * y =\n{x*y}")

x * y =
[[0 1]
 [0 3]]
