# Mastering NumPy - 1. Working with NumPy Arrays

## 1.5 Basics of NumPy Array Objects

In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print("We just create a", type(x))

We just create a <class 'numpy.ndarray'>


In [7]:
print("Our template has shape as:", x.shape)

Our template has shape as: (2, 3)


In [8]:
print("Total size is:", x.size)

Total size is: 6


In [9]:
print("The dimension of our array is", x.ndim)

The dimension of our array is 2


In [10]:
print("Data type of elements are", x.dtype)

Data type of elements are int64


In [11]:
print("It consumes", x.nbytes, "bytes")

It consumes 48 bytes


In [14]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.float)
print(x)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [15]:
x = np.array([[1,2,3],[4,5,6]], dtype=float)
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [17]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.complex)
print(x)

AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [20]:
x = np.array([[1,2,3],[4,5,6]], dtype=complex)
print(x)
print("X consumes:", x.nbytes, "bytes")

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
X consumes: 96 bytes


In [23]:
x = np.array([[1,2,3], [4,5,6]], dtype = np.uint32)
print(x)
print(x.nbytes)

[[1 2 3]
 [4 5 6]]
24


In [22]:
x = np.array([[1,2,3], [4,5,6]], dtype = uint32)
print(x)
print(x.nbytes)

NameError: name 'uint32' is not defined

In [24]:
x = np.array([[1,2,3], [4,5,6]], dtype = np.int64)
print(x)
print(x.nbytes)

[[1 2 3]
 [4 5 6]]
48


In [25]:
x_copy = np.array(x, dtype = float)
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
x_copy_int = x_copy.astype(int)
print("x_copy_int =", x_copy_int)
print("x_copy =", x_copy)

x_copy_int = [[1 2 3]
 [4 5 6]]
x_copy = [[1. 2. 3.]
 [4. 5. 6.]]
