# Mastering NumPy - 1. Working with NumPy Arrays

## 1.4 Introduction of NumPy Array Objects

### 1.4.3 Matrix Multiplication

In [3]:
import numpy as np
x = np.array([
    [1, 0, 4],
    [3, 3, 1]
])
y = np.array([
    [2, 5],
    [1, 1],
    [3, 2]
])
print(x.dot(y))

[[14 13]
 [12 20]]


## 1.5 Basics of NumPy Array Objects

In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print("We just create a", type(x))

We just create a <class 'numpy.ndarray'>


In [7]:
print("Our template has shape as:", x.shape)

Our template has shape as: (2, 3)


In [8]:
print("Total size is:", x.size)

Total size is: 6


In [9]:
print("The dimension of our array is", x.ndim)

The dimension of our array is 2


In [10]:
print("Data type of elements are", x.dtype)

Data type of elements are int64


In [11]:
print("It consumes", x.nbytes, "bytes")

It consumes 48 bytes


In [14]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.float)
print(x)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [15]:
x = np.array([[1,2,3],[4,5,6]], dtype=float)
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [17]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.complex)
print(x)

AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [20]:
x = np.array([[1,2,3],[4,5,6]], dtype=complex)
print(x)
print("X consumes:", x.nbytes, "bytes")

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
X consumes: 96 bytes


In [23]:
x = np.array([[1,2,3], [4,5,6]], dtype = np.uint32)
print(x)
print(x.nbytes)

[[1 2 3]
 [4 5 6]]
24


In [22]:
x = np.array([[1,2,3], [4,5,6]], dtype = uint32)
print(x)
print(x.nbytes)

NameError: name 'uint32' is not defined

In [24]:
x = np.array([[1,2,3], [4,5,6]], dtype = np.int64)
print(x)
print(x.nbytes)

[[1 2 3]
 [4 5 6]]
48


In [25]:
x_copy = np.array(x, dtype = float)
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
x_copy_int = x_copy.astype(int)
print("x_copy_int =", x_copy_int)
print("x_copy =", x_copy)

x_copy_int = [[1 2 3]
 [4 5 6]]
x_copy = [[1. 2. 3.]
 [4. 5. 6.]]


## 1.6 NumPy Array Operations

In [29]:
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
print(type(my_list), type(my_array))

<class 'list'> <class 'numpy.ndarray'>


In [30]:
my_array + 2

array([ 4, 16,  8, 10])

In [31]:
my_array - 1

array([ 1, 13,  5,  7])

In [32]:
my_array * 2

array([ 4, 28, 12, 16])

In [33]:
my_array / 2

array([1., 7., 3., 4.])

In [37]:
second_array = np.zeros(4)+3
second_array

array([3., 3., 3., 3.])

In [38]:
my_array - second_array

array([-1., 11.,  3.,  5.])

In [39]:
second_array / my_array

array([1.5       , 0.21428571, 0.5       , 0.375     ])

In [42]:
second_array = np.ones(4) + 3
second_array

array([4., 4., 4., 4.])

In [43]:
my_array - second_array

array([-2., 10.,  2.,  4.])

In [44]:
second_array / my_array

array([2.        , 0.28571429, 0.66666667, 0.5       ])

In [45]:
second_array = np.identity(4)
second_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
second_array = np.identity(4) + 3
second_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [51]:
my_array - second_array

array([[-2., 11.,  3.,  5.],
       [-1., 10.,  3.,  5.],
       [-1., 11.,  2.,  5.],
       [-1., 11.,  3.,  4.]])

In [52]:
second_array / my_array

array([[2.        , 0.21428571, 0.5       , 0.375     ],
       [1.5       , 0.28571429, 0.5       , 0.375     ],
       [1.5       , 0.21428571, 0.66666667, 0.375     ],
       [1.5       , 0.21428571, 0.5       , 0.5       ]])

In [54]:
x = np.arange(3, 7, 0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [56]:
x = np.linspace(1.2, 40.5, num = 20)
x

array([ 1.2       ,  3.26842105,  5.33684211,  7.40526316,  9.47368421,
       11.54210526, 13.61052632, 15.67894737, 17.74736842, 19.81578947,
       21.88421053, 23.95263158, 26.02105263, 28.08947368, 30.15789474,
       32.22631579, 34.29473684, 36.36315789, 38.43157895, 40.5       ])