# Mastering NumPy - 1. Working with NumPy Arrays

## 1.7 Working with Multi-Dimensional Arrays

In [3]:
# Matrix multiplication in NumPy use `dot()` instead of `*`
c = np.ones((4,4))
c*c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [11]:
# Stacking Arrays
y = np.arange(15).reshape(3,5)
x = np.arange(10).reshape(2,5)
print(f"y = {y},\nx = {x}")

y = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]],
x = [[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
new_array_h = np.hstack((y,x))
new_array_h

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [15]:
new_array_v = np.vstack((y,x))
new_array_v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [16]:
y = np.arange(15).reshape(5,3)
x = np.arange(10).reshape(5,2)
print(f"y = {y},\nx = {x}")

y = [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]],
x = [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
new_array_h = np.hstack((y,x))
new_array_h

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [18]:
new_array_v = np.vstack((y,x))
new_array_v

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [25]:
# Get 100 rows and 10 columns
from scipy import stats
x = np.random.rand(100,10)
n,min_max,mean,var,skew,kurt = stats.describe(x)
new_array = np.vstack((mean,var,skew,kurt,min_max[0],min_max[1]))
new_array.T

array([[ 4.86050247e-01,  9.33103280e-02,  1.87622454e-01,
        -1.40470721e+00,  1.04802259e-02,  9.69919831e-01],
       [ 4.80997575e-01,  7.61145660e-02,  8.56999354e-02,
        -1.13811153e+00,  2.92317535e-03,  9.91047348e-01],
       [ 5.12092537e-01,  8.60405732e-02, -9.83749300e-02,
        -1.29001649e+00,  1.38144618e-02,  9.90484059e-01],
       [ 5.03968974e-01,  8.97576355e-02, -2.16469343e-01,
        -1.30307016e+00,  3.02310191e-03,  9.65438131e-01],
       [ 5.03422150e-01,  8.80409351e-02, -6.26439715e-02,
        -1.27052156e+00,  7.02208008e-04,  9.94199877e-01],
       [ 5.13301395e-01,  8.47047246e-02, -1.63114548e-01,
        -1.20318839e+00,  8.79709576e-03,  9.83907101e-01],
       [ 4.92890831e-01,  7.69157933e-02,  7.69531176e-02,
        -1.14535362e+00,  7.43762673e-03,  9.78924588e-01],
       [ 4.96388514e-01,  8.45193146e-02, -4.66410211e-02,
        -1.24443533e+00,  1.78340556e-03,  9.95983438e-01],
       [ 5.31116403e-01,  8.88812196e-02, -1.226

In [ ]:
# mask: numpy.ma
# when NumPy masks, it will be treated as an invalid
# and does not take into account computation
import numpy.ma as ma
x = np.arange(6)
print(x, x.mean())
masked_array = ma.masked_array(x, mask=[1,0,0,0,0,0])
print(masked_array.mean())

[0 1 2 3 4 5] 2.5
3.0


In [30]:
x = np.arange(25, dtype = float).reshape(5,5)
x[x<5] = np.nan
x

array([[nan, nan, nan, nan, nan],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [33]:
np.where(np.isnan(x), ma.array(x, mask = np.isnan(x)).mean(axis=0), x)

array([[12.5, 13.5, 14.5, 15.5, 16.5],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [15. , 16. , 17. , 18. , 19. ],
       [20. , 21. , 22. , 23. , 24. ]])