# 6.1 NumPy and Array Computing

In [1]:
v = (v0, v1, ... vn-1)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (328407154.py, line 1)

In [3]:
v0, v1, v2, v3, v4, v5 = 1
v = [v0, v1, v2, v3, v4, v5]

TypeError: cannot unpack non-iterable int object

In [4]:
Aij = [
    [0, 7, -3, 5],
    [-1, -3, 4, 0],
    [8, 3, 5, -7]
]

## Storing `(x,y)` points one a curve in lists and arrays

In [6]:
def f(x):
    return x**2

n = 5
dx = 1.0/(n-1)
xlist = [i*dx for i in range(n)]
print(xlist)
ylist = [f(x) for x in xlist]
print(ylist)

[0.0, 0.25, 0.5, 0.75, 1.0]
[0.0, 0.0625, 0.25, 0.5625, 1.0]


In [13]:
def f(x):
    return x**2

n = 11
dx = 20.0/(n-1)
xlist = [i*dx for i in range(n)]
print(xlist, type(xlist))
ylist = [f(x) for x in xlist]
print(ylist)

[0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0] <class 'list'>
[0.0, 4.0, 16.0, 36.0, 64.0, 100.0, 144.0, 196.0, 256.0, 324.0, 400.0]


In [14]:
import numpy as np
x = np.array(xlist)
print(x, type(x))
y = np.array(ylist)
print(y, type(y))

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.] <class 'numpy.ndarray'>
[  0.   4.  16.  36.  64. 100. 144. 196. 256. 324. 400.] <class 'numpy.ndarray'>


In [17]:
import numpy as np
def f(x):
    return x**2

n = 5
x = np.linspace(0, 1, n)
print(x)
y = np.zeros(n)
print(y)
for i in range(n):
    y[i] = f(x[i])
print(y)

[0.   0.25 0.5  0.75 1.  ]
[0. 0. 0. 0. 0.]
[0.     0.0625 0.25   0.5625 1.    ]


In [24]:
import numpy as np
from math import cos
n = 11
x = np.linspace(0, 1, n)
y = np.zeros(n)
print(x, len(x))
print(y, len(y))
for i in range(len(x)):
    y[i] = cos(x[i])
    print(i)
print(y)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 11
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 11
0
1
2
3
4
5
6
7
8
9
10
[1.         0.99500417 0.98006658 0.95533649 0.92106099 0.87758256
 0.82533561 0.76484219 0.69670671 0.62160997 0.54030231]


In [25]:
import numpy as np
from math import cos
n = 11
x = np.linspace(0, 1, n)
print(x, len(x))
y = np.cos(x)
print(y, len(y))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 11
[1.         0.99500417 0.98006658 0.95533649 0.92106099 0.87758256
 0.82533561 0.76484219 0.69670671 0.62160997 0.54030231] 11


In [27]:
from numpy import sin, exp, linspace

def g(x):
    return x**2 + 2*x - 4

def f(x):
    return sin(x)*exp(-2*x)

x = 1.2
y = f(x)
print(x, y)

x = linspace(0, 3, 101)
y = f(x)
z = g(x)
print(x, '\n', y, '\n', z)

1.2 0.08455267826468156
[0.   0.03 0.06 0.09 0.12 0.15 0.18 0.21 0.24 0.27 0.3  0.33 0.36 0.39
 0.42 0.45 0.48 0.51 0.54 0.57 0.6  0.63 0.66 0.69 0.72 0.75 0.78 0.81
 0.84 0.87 0.9  0.93 0.96 0.99 1.02 1.05 1.08 1.11 1.14 1.17 1.2  1.23
 1.26 1.29 1.32 1.35 1.38 1.41 1.44 1.47 1.5  1.53 1.56 1.59 1.62 1.65
 1.68 1.71 1.74 1.77 1.8  1.83 1.86 1.89 1.92 1.95 1.98 2.01 2.04 2.07
 2.1  2.13 2.16 2.19 2.22 2.25 2.28 2.31 2.34 2.37 2.4  2.43 2.46 2.49
 2.52 2.55 2.58 2.61 2.64 2.67 2.7  2.73 2.76 2.79 2.82 2.85 2.88 2.91
 2.94 2.97 3.  ] 
 [0.         0.0282487  0.0531833  0.07507287 0.09416896 0.11070649
 0.1249047  0.13696791 0.14708644 0.15543728 0.16218493 0.16748207
 0.17147028 0.17428065 0.17603448 0.17684379 0.17681196 0.17603425
 0.17459828 0.17258459 0.17006704 0.16711328 0.16378516 0.1601391
 0.15622653 0.15209417 0.14778437 0.14333549 0.1387821  0.13415532
 0.12948307 0.12479028 0.12009919 0.11542947 0.11079851 0.10622155
 0.10171189 0.09728104 0.09293886 0.08869373 0.08455268 0.0

In [33]:
import numpy, math
x = numpy.linspace(0, 1, 6)
print(x, type(x))
print(math.cos(x[0]))
print(numpy.cos(x[0]))
print(numpy.cos(x))
print(math.cos(x))


[0.  0.2 0.4 0.6 0.8 1. ] <class 'numpy.ndarray'>
1.0
1.0
[1.         0.98006658 0.92106099 0.82533561 0.69670671 0.54030231]


TypeError: only length-1 arrays can be converted to Python scalars

In [34]:
import numpy as np
n = 100
x = np.linspace(0, 4, n+1)
y = np.exp(-x)*np.sin(2*np.pi*x)
print(x)
print(y)

[0.   0.04 0.08 0.12 0.16 0.2  0.24 0.28 0.32 0.36 0.4  0.44 0.48 0.52
 0.56 0.6  0.64 0.68 0.72 0.76 0.8  0.84 0.88 0.92 0.96 1.   1.04 1.08
 1.12 1.16 1.2  1.24 1.28 1.32 1.36 1.4  1.44 1.48 1.52 1.56 1.6  1.64
 1.68 1.72 1.76 1.8  1.84 1.88 1.92 1.96 2.   2.04 2.08 2.12 2.16 2.2
 2.24 2.28 2.32 2.36 2.4  2.44 2.48 2.52 2.56 2.6  2.64 2.68 2.72 2.76
 2.8  2.84 2.88 2.92 2.96 3.   3.04 3.08 3.12 3.16 3.2  3.24 3.28 3.32
 3.36 3.4  3.44 3.48 3.52 3.56 3.6  3.64 3.68 3.72 3.76 3.8  3.84 3.88
 3.92 3.96 4.  ]
[ 0.00000000e+00  2.38938617e-01  4.44714691e-01  6.07138818e-01
  7.19488798e-01  7.78659218e-01  7.85075631e-01  7.42396734e-01
  6.57039293e-01  5.37568848e-01  3.94004237e-01  2.37085619e-01
  7.75541234e-02 -7.45131827e-02 -2.10276081e-01 -3.22583386e-01
 -4.06285796e-01 -4.58400760e-01 -4.78130535e-01 -4.66743594e-01
 -4.27337239e-01 -3.64505251e-01 -2.83938442e-01 -1.91988012e-01
 -9.52215886e-02 -9.01044760e-17  8.79006050e-02  1.63601392e-01
  2.23353889e-01  2.64685137e-01