# 6.5 More Array Operations

## 6.5.1 Create Same Size Array as Another Array

In [1]:
import numpy as np

x = np.linspace(0, 10, 11)
print(x, type(x))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] <class 'numpy.ndarray'>


In [3]:
a = np.zeros(x.shape, x.dtype)
print(a, type(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [4]:
a = x.copy()
print(a, type(a))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] <class 'numpy.ndarray'>


In [5]:
a = np.zeros_like(x)
print(a, type(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [7]:
a = np.asarray(a)
print(a, type(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [8]:
b = [1,2,3,4,5]
c = np.asarray(b)
print(b, type(b))
print(c, type(c))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


## 6.5.2 Array Slicing

In [9]:
a = np.linspace(1,8,8)
print(a)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [10]:
a[[1,6,7]] = 10
print(a)

[ 1. 10.  3.  4.  5.  6. 10. 10.]


In [11]:
a[range(2,8,3)] = -2
print(a)

[ 1. 10. -2.  4.  5. -2. 10. 10.]


In [12]:
print(a<0)

[False False  True False False  True False False]


In [13]:
print(a>0)

[ True  True False  True  True False  True  True]


In [14]:
print(a[a<0])

[-2. -2.]


In [15]:
a[a<0] = a.max()
print(a)

[ 1. 10. 10.  4.  5. 10. 10. 10.]


## 6.5.3 Multi-Dimensional Array

In [17]:
A = np.zeros((3,4))
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
A[0,0] = -1
A[1,0] = 1
print(A)

[[-1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [19]:
A[2][3] = 100
print(A)

[[ -1.   0.   0.   0.]
 [  1.   0.   0.   0.]
 [  0.   0.   0. 100.]]


In [20]:
A = np.zeros(((3,4,5)))
print(A)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [21]:
A[1][2][3] = 100
print(A)

[[[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0. 100.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]]
