## 2.1 Vector and Matrix Mathematics

In [1]:
import numpy as np
a = np.arange(12).reshape(3,2)
print(f"a=\n{a}")

ValueError: cannot reshape array of size 12 into shape (3,2)

In [3]:
a = np.arange(6).reshape(3,2)
b = np.arange(10).reshape(2,5)
print(f"a=\n{a}")
print(f"b=\n{b}")

a=
[[0 1]
 [2 3]
 [4 5]]
b=
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
print(f"{np.dot(a,b)}\n{np.matmul(a,b)}\n{a@b}")

[[ 5  6  7  8  9]
 [15 20 25 30 35]
 [25 34 43 52 61]]
[[ 5  6  7  8  9]
 [15 20 25 30 35]
 [25 34 43 52 61]]
[[ 5  6  7  8  9]
 [15 20 25 30 35]
 [25 34 43 52 61]]
