# Import the relevant libraries

In [1]:
import numpy as np

# Declaring scalars, vectors, and matrices

## Scalars

In [2]:
s = 5
s

5

## Vectors

In [3]:
v = np.array([5,-2,4]) # this is one row-vector by default
v

array([ 5, -2,  4])

## Matrices

In [4]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [5]:
type(s)

int

In [6]:
type(v) # 1-dimensional array

numpy.ndarray

In [7]:
type(m) # 2-dimensional array

numpy.ndarray

In [9]:
s_array = np.array(5)
s_array

array(5)

In [10]:
type(s_array)

numpy.ndarray

## Data shapes

In [11]:
m.shape

(2, 3)

In [12]:
v.shape

(3,)

In [13]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [16]:
s_array.shape

()

## Creating a column vector

In [14]:
v.reshape(1,3) # row-vector

array([[ 5, -2,  4]])

In [15]:
v.reshape(3,1) # column-vector

array([[ 5],
       [-2],
       [ 4]])