<hr style="border:5px solid #108999"> </hr>

# Mathematics for Python <hr style="border:4.5px solid #108999"> </hr>

## Arrays in Python

### Declaring Scalars, Vectors, and Matrices

#### Import the Relevant Libraries

In [1]:
import numpy as np

#### Scalars

In [2]:
s = 5

In [3]:
s

5

#### Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

#### Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

#### Data Types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array([5])

#### Data Shapes

In [12]:
m.shape

(2, 3)

In [13]:
v.shape

(3,)

In [14]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [15]:
s_array.shape

(1,)

#### Creating a Column Vector

In [16]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [17]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [18]:
m+s

array([[10, 17, 11],
       [ 2,  5, 19]])

In [19]:
m+s_array

array([[10, 17, 11],
       [ 2,  5, 19]])

In [20]:
v+s

array([10,  3,  9])

In [21]:
v

array([ 5, -2,  4])

In [22]:
v+s_array

array([10,  3,  9])

In [23]:
m+v

array([[10, 10, 10],
       [ 2, -2, 18]])

## What is a Tensor

### Import the Relevant Libraries

In [1]:
import numpy as np

### Creating a Tensor

In [24]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [25]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [26]:
t = np.array([m1,m2])

In [27]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Checking its Shape

In [28]:
t.shape

(2, 2, 3)

### Manually Creating a Tensor

In [30]:
t_manual = np.array([[[ 5, 12,  6], [-3,  0, 14]], [[ 9,  8,  7], [ 1,  3, -5]]])

In [31]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Adding and Subtracting Matrices

### Import the Relevant Libraries

In [1]:
import numpy as np

### Addition

In [32]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [33]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [34]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

### Difference

#### Example 1

In [35]:
m3 = np.array([[5,3],[-2,4]])
m4 = np.array([[7,-5],[3,8]])

In [36]:
m3

array([[ 5,  3],
       [-2,  4]])

In [37]:
m4

array([[ 7, -5],
       [ 3,  8]])

In [38]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

#### Example 2

In [39]:
m5 = np.array([[22.33,-4.73],[-203.14,1200.02],[4.22,234.1]])
m5

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [40]:
m6 = np.array([[131.13,448.29],[-340.21,1.06],[30.41,424.99]])
m6

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [41]:
m5 - m6

array([[-108.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

### Adding Vectors Together

In [42]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [43]:
v1 + v2

array([6, 6, 6, 6, 6])

In [44]:
v1 - v2

array([-4, -2,  0,  2,  4])

## Errors When Adding Matrices

### Import the Relevant Libraries

In [1]:
import numpy as np

### Addition

#### Addition of Scalars

In [45]:
5 + 5

10

In [46]:
10 - 4

6

#### Addition of Matrices

In [47]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [48]:
m3 = np.array([[5,3],[-2,4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [49]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

#### Addition of Vectors

In [50]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [51]:
v3 = np.array([1,2,3])
v3

array([1, 2, 3])

In [52]:
v1 + v3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

#### Exceptions (Addition with a Scalar)

In [53]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [54]:
m1 + 1 

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [55]:
v1

array([1, 2, 3, 4, 5])

In [56]:
v1 + 1

array([2, 3, 4, 5, 6])

In [57]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [58]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])

## Transpose

### Import the Relevant Libraries

In [1]:
import numpy as np

### Transposing Matrices

In [59]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [60]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [65]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [66]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [63]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [64]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

### Transposing Scalars

In [67]:
s = np.array([5])

In [68]:
s.T

array([5])

### Transposing Vectors

In [69]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [72]:
x.T

array([1, 2, 3])

In [73]:
x.shape

(3,)

In [74]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [75]:
x_reshaped.T

array([[1],
       [2],
       [3]])

## Dot Product of Vectors

### Import the Relevant Libraries

In [1]:
import numpy as np

### Dot Product

In [76]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [77]:
np.dot(x,y) 

-66

In [78]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [79]:
np.dot(u,v)

18

### Scalar * Scalar

In [80]:
np.dot(5,6)

30

In [81]:
np.dot(10,-2)

-20

### Scalar * Vector

In [82]:
x

array([ 2,  8, -4])

In [83]:
5*x

array([ 10,  40, -20])

## Dot Product of Vectors

### Import the Relevant Libraries

In [1]:
import numpy as np

### Scalar * Matrix

In [84]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [85]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

### Matrix * Matrix

#### Example 1

In [86]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [87]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])

#### Example 2

In [88]:
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [89]:
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [90]:
np.dot(C,D)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])